import type { ComponentType } from 'react';
import { FaLinkedin } from 'react-icons/fa6';
import {
  SiX,
  SiInstagram,
  SiYoutube,
  SiGithub,
  SiFacebook,
  SiThreads,
  SiSnapchat,
  SiPinterest,
  SiReddit,
  SiDiscord,
  SiTwitch,
  SiTelegram,
  SiWhatsapp,
  SiSignal,
  SiLine,
  SiWechat,
  SiMedium,
  SiSubstack,
  SiBehance,
  SiDribbble,
  SiSpotify,
  SiSoundcloud,
  SiBandcamp,
  SiApplemusic,
  SiMastodon,
  SiBluesky,
  SiTumblr,
  SiVimeo,
  SiPatreon,
  SiKofi,
  SiBuymeacoffee,
  SiGumroad,
  SiCashapp,
  SiVenmo,
  SiQuora,
  SiFlickr,
  SiVsco,
  SiClubhouse,
  SiBereal,
  SiLetterboxd,
  SiGoodreads,
  SiProducthunt,
  SiDevdotto,
  SiStackoverflow,
  SiFigma,
  SiNotion,
  SiSteam,
  SiKick,
  SiRumble,
  SiStrava,
  SiTiktok,
} from 'react-icons/si';

export const SOCIAL_PLATFORM_ICONS: Record<
  string,
  ComponentType<{ className?: string }>
> = {
  x: SiX,
  instagram: SiInstagram,
  youtube: SiYoutube,
  linkedin: FaLinkedin,
  github: SiGithub,
  facebook: SiFacebook,
  threads: SiThreads,
  snapchat: SiSnapchat,
  pinterest: SiPinterest,
  reddit: SiReddit,
  discord: SiDiscord,
  twitch: SiTwitch,
  telegram: SiTelegram,
  whatsapp: SiWhatsapp,
  signal: SiSignal,
  line: SiLine,
  wechat: SiWechat,
  medium: SiMedium,
  substack: SiSubstack,
  behance: SiBehance,
  dribbble: SiDribbble,
  spotify: SiSpotify,
  soundcloud: SiSoundcloud,
  bandcamp: SiBandcamp,
  'apple-music': SiApplemusic,
  mastodon: SiMastodon,
  bluesky: SiBluesky,
  tumblr: SiTumblr,
  vimeo: SiVimeo,
  patreon: SiPatreon,
  kofi: SiKofi,
  buymeacoffee: SiBuymeacoffee,
  gumroad: SiGumroad,
  cashapp: SiCashapp,
  venmo: SiVenmo,
  quora: SiQuora,
  flickr: SiFlickr,
  vsco: SiVsco,
  clubhouse: SiClubhouse,
  bereal: SiBereal,
  letterboxd: SiLetterboxd,
  goodreads: SiGoodreads,
  producthunt: SiProducthunt,
  devto: SiDevdotto,
  stackoverflow: SiStackoverflow,
  figma: SiFigma,
  notion: SiNotion,
  steam: SiSteam,
  kick: SiKick,
  rumble: SiRumble,
  strava: SiStrava,
  tiktok: SiTiktok,
};
