export interface CountryDialCode {
  iso2: string;
  name: string;
  dialCode: string;
  flagEmoji: string;
}

export const COUNTRIES: CountryDialCode[] = [
  { iso2: 'IN', name: 'India', dialCode: '+91', flagEmoji: '🇮🇳' },
  { iso2: 'US', name: 'United States', dialCode: '+1', flagEmoji: '🇺🇸' },
  { iso2: 'GB', name: 'United Kingdom', dialCode: '+44', flagEmoji: '🇬🇧' },
  { iso2: 'CA', name: 'Canada', dialCode: '+1', flagEmoji: '🇨🇦' },
  { iso2: 'AU', name: 'Australia', dialCode: '+61', flagEmoji: '🇦🇺' },
  { iso2: 'DE', name: 'Germany', dialCode: '+49', flagEmoji: '🇩🇪' },
  { iso2: 'FR', name: 'France', dialCode: '+33', flagEmoji: '🇫🇷' },
  { iso2: 'IT', name: 'Italy', dialCode: '+39', flagEmoji: '🇮🇹' },
  { iso2: 'ES', name: 'Spain', dialCode: '+34', flagEmoji: '🇪🇸' },
  { iso2: 'PT', name: 'Portugal', dialCode: '+351', flagEmoji: '🇵🇹' },
  { iso2: 'NL', name: 'Netherlands', dialCode: '+31', flagEmoji: '🇳🇱' },
  { iso2: 'BE', name: 'Belgium', dialCode: '+32', flagEmoji: '🇧🇪' },
  { iso2: 'CH', name: 'Switzerland', dialCode: '+41', flagEmoji: '🇨🇭' },
  { iso2: 'AT', name: 'Austria', dialCode: '+43', flagEmoji: '🇦🇹' },
  { iso2: 'SE', name: 'Sweden', dialCode: '+46', flagEmoji: '🇸🇪' },
  { iso2: 'NO', name: 'Norway', dialCode: '+47', flagEmoji: '🇳🇴' },
  { iso2: 'DK', name: 'Denmark', dialCode: '+45', flagEmoji: '🇩🇰' },
  { iso2: 'FI', name: 'Finland', dialCode: '+358', flagEmoji: '🇫🇮' },
  { iso2: 'IE', name: 'Ireland', dialCode: '+353', flagEmoji: '🇮🇪' },
  { iso2: 'PL', name: 'Poland', dialCode: '+48', flagEmoji: '🇵🇱' },
  { iso2: 'GR', name: 'Greece', dialCode: '+30', flagEmoji: '🇬🇷' },
  { iso2: 'RU', name: 'Russia', dialCode: '+7', flagEmoji: '🇷🇺' },
  { iso2: 'UA', name: 'Ukraine', dialCode: '+380', flagEmoji: '🇺🇦' },
  { iso2: 'TR', name: 'Turkey', dialCode: '+90', flagEmoji: '🇹🇷' },
  { iso2: 'CN', name: 'China', dialCode: '+86', flagEmoji: '🇨🇳' },
  { iso2: 'JP', name: 'Japan', dialCode: '+81', flagEmoji: '🇯🇵' },
  { iso2: 'KR', name: 'South Korea', dialCode: '+82', flagEmoji: '🇰🇷' },
  { iso2: 'SG', name: 'Singapore', dialCode: '+65', flagEmoji: '🇸🇬' },
  { iso2: 'MY', name: 'Malaysia', dialCode: '+60', flagEmoji: '🇲🇾' },
  { iso2: 'ID', name: 'Indonesia', dialCode: '+62', flagEmoji: '🇮🇩' },
  { iso2: 'TH', name: 'Thailand', dialCode: '+66', flagEmoji: '🇹🇭' },
  { iso2: 'VN', name: 'Vietnam', dialCode: '+84', flagEmoji: '🇻🇳' },
  { iso2: 'PH', name: 'Philippines', dialCode: '+63', flagEmoji: '🇵🇭' },
  { iso2: 'PK', name: 'Pakistan', dialCode: '+92', flagEmoji: '🇵🇰' },
  { iso2: 'BD', name: 'Bangladesh', dialCode: '+880', flagEmoji: '🇧🇩' },
  { iso2: 'LK', name: 'Sri Lanka', dialCode: '+94', flagEmoji: '🇱🇰' },
  { iso2: 'NP', name: 'Nepal', dialCode: '+977', flagEmoji: '🇳🇵' },
  { iso2: 'AE', name: 'United Arab Emirates', dialCode: '+971', flagEmoji: '🇦🇪' },
  { iso2: 'SA', name: 'Saudi Arabia', dialCode: '+966', flagEmoji: '🇸🇦' },
  { iso2: 'QA', name: 'Qatar', dialCode: '+974', flagEmoji: '🇶🇦' },
  { iso2: 'KW', name: 'Kuwait', dialCode: '+965', flagEmoji: '🇰🇼' },
  { iso2: 'IL', name: 'Israel', dialCode: '+972', flagEmoji: '🇮🇱' },
  { iso2: 'EG', name: 'Egypt', dialCode: '+20', flagEmoji: '🇪🇬' },
  { iso2: 'ZA', name: 'South Africa', dialCode: '+27', flagEmoji: '🇿🇦' },
  { iso2: 'NG', name: 'Nigeria', dialCode: '+234', flagEmoji: '🇳🇬' },
  { iso2: 'KE', name: 'Kenya', dialCode: '+254', flagEmoji: '🇰🇪' },
  { iso2: 'GH', name: 'Ghana', dialCode: '+233', flagEmoji: '🇬🇭' },
  { iso2: 'BR', name: 'Brazil', dialCode: '+55', flagEmoji: '🇧🇷' },
  { iso2: 'MX', name: 'Mexico', dialCode: '+52', flagEmoji: '🇲🇽' },
  { iso2: 'AR', name: 'Argentina', dialCode: '+54', flagEmoji: '🇦🇷' },
  { iso2: 'CL', name: 'Chile', dialCode: '+56', flagEmoji: '🇨🇱' },
  { iso2: 'CO', name: 'Colombia', dialCode: '+57', flagEmoji: '🇨🇴' },
  { iso2: 'PE', name: 'Peru', dialCode: '+51', flagEmoji: '🇵🇪' },
  { iso2: 'NZ', name: 'New Zealand', dialCode: '+64', flagEmoji: '🇳🇿' },
] as const;

export const DEFAULT_COUNTRY_ISO2 = 'IN';
