export const VIDEO_FEED_PAGE_SIZE = 12;
export const SHORTS_FEED_PAGE_SIZE = 20;
export const SHORTS_PREFETCH_THRESHOLD = 3;
export const POSTS_FEED_PAGE_SIZE = 10;
export const UNIFIED_FEED_PAGE_SIZE = 12;
export const UNIFIED_FEED_VIDEO_WEIGHT = 0.6;
export const CHAT_RAIL_WIDTH_PX = 320;
export const SHORT_THEATER_WIDTH_PX = 384;

export const FEED_VIDEOS_PER_BLOCK_FIRST_MOBILE_PORTRAIT = 2;
export const FEED_VIDEOS_PER_BLOCK_MOBILE_PORTRAIT = 4;
export const FEED_SHORTS_PER_BLOCK_MOBILE_PORTRAIT = 2;

export const FEED_VIDEOS_PER_BLOCK_FIRST_COMPACT = 4;
export const FEED_VIDEOS_PER_BLOCK_COMPACT = 6;
export const FEED_SHORTS_PER_BLOCK_COMPACT = 4;

export const FEED_VIDEOS_PER_BLOCK_FIRST_TABLET_LANDSCAPE = 3;
export const FEED_VIDEOS_PER_BLOCK_TABLET_LANDSCAPE = 6;
export const FEED_SHORTS_PER_BLOCK_TABLET_LANDSCAPE = 5;

export const FEED_VIDEOS_PER_BLOCK_FIRST_DESKTOP = 3;
export const FEED_VIDEOS_PER_BLOCK_DESKTOP = 6;
export const FEED_SHORTS_PER_BLOCK_DESKTOP = 5;
