export const REDIS_RECONNECT_MAX_ATTEMPTS = 10;
export const REDIS_RECONNECT_BACKOFF_STEP_MS = 50;
export const REDIS_RECONNECT_BACKOFF_CAP_MS = 2000;

export const BULLMQ_WORKER_ERROR_MAX_ATTEMPTS = 10;
export const BULLMQ_WORKER_ERROR_BACKOFF_STEP_MS = 1000;
export const BULLMQ_WORKER_ERROR_BACKOFF_CAP_MS = 30000;
