export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  OTP_VERIFICATION_REQUIRED: 'OTP_VERIFICATION_REQUIRED',
  PRIVATE_ACCOUNT: 'PRIVATE_ACCOUNT',
  EDIT_WINDOW_EXPIRED: 'EDIT_WINDOW_EXPIRED',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
