import { Router } from 'express';
import authRoutes from './modules/auth/auth.routes.js';
import videoRoutes from './modules/video/video.routes.js';
import shortRoutes from './modules/short/short.routes.js';
import postRoutes from './modules/post/post.routes.js';
import creatorRoutes from './modules/creator/creator.routes.js';
import webhookRoutes from './modules/webhook/webhook.routes.js';
import uploadRoutes from './modules/upload/upload.routes.js';
import feedRoutes from './modules/feed/feed.routes.js';
import userRoutes from './modules/user/user.routes.js';
import preferencesRoutes from './modules/preferences/preferences.routes.js';
import accountRoutes from './modules/account/account.routes.js';
import historyRoutes from './modules/history/history.routes.js';
import searchRoutes from './modules/search/search.routes.js';
import reportRoutes from './modules/report/report.routes.js';
import juryRoutes from './modules/jury/jury.routes.js';
import followRoutes from './modules/follow/follow.routes.js';
import likeRoutes from './modules/like/like.routes.js';
import shareRoutes from './modules/share/share.routes.js';
import commentRoutes from './modules/comment/comment.routes.js';
import playlistRoutes from './modules/playlist/playlist.routes.js';
import bookmarkRoutes from './modules/bookmark/bookmark.routes.js';
import notificationRoutes from './modules/notification/notification.routes.js';
import keyBundleRoutes from './modules/message/routes/keyBundle.routes.js';
import conversationRoutes from './modules/message/routes/conversation.routes.js';
import messageRoutes from './modules/message/routes/message.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/video', videoRoutes);
router.use('/short', shortRoutes);
router.use('/post', postRoutes);
router.use('/creator', creatorRoutes);
router.use('/webhook', webhookRoutes);
router.use('/uploads', uploadRoutes);
router.use('/feed', feedRoutes);
router.use('/user', userRoutes);
router.use('/preferences', preferencesRoutes);
router.use('/account', accountRoutes);
router.use('/history', historyRoutes);
router.use('/search', searchRoutes);
router.use('/reports', reportRoutes);
router.use('/jury', juryRoutes);
router.use('/follow', followRoutes);
router.use('/likes', likeRoutes);
router.use('/share', shareRoutes);
router.use('/comments', commentRoutes);
router.use('/playlists', playlistRoutes);
router.use('/bookmarks', bookmarkRoutes);
router.use('/notifications', notificationRoutes);
router.use('/keys', keyBundleRoutes);
router.use('/conversations', conversationRoutes);
router.use('/messages', messageRoutes);

export default router;
