export interface SocialPlatformCatalogEntry {
  key: string;
  name: string;
}

export const SOCIAL_PLATFORM_CATALOG: SocialPlatformCatalogEntry[] = [
  { key: 'x', name: 'X' },
  { key: 'instagram', name: 'Instagram' },
  { key: 'youtube', name: 'YouTube' },
  { key: 'linkedin', name: 'LinkedIn' },
  { key: 'github', name: 'GitHub' },
  { key: 'facebook', name: 'Facebook' },
  { key: 'threads', name: 'Threads' },
  { key: 'snapchat', name: 'Snapchat' },
  { key: 'pinterest', name: 'Pinterest' },
  { key: 'reddit', name: 'Reddit' },
  { key: 'discord', name: 'Discord' },
  { key: 'twitch', name: 'Twitch' },
  { key: 'telegram', name: 'Telegram' },
  { key: 'whatsapp', name: 'WhatsApp' },
  { key: 'signal', name: 'Signal' },
  { key: 'line', name: 'Line' },
  { key: 'wechat', name: 'WeChat' },
  { key: 'medium', name: 'Medium' },
  { key: 'substack', name: 'Substack' },
  { key: 'behance', name: 'Behance' },
  { key: 'dribbble', name: 'Dribbble' },
  { key: 'spotify', name: 'Spotify' },
  { key: 'soundcloud', name: 'SoundCloud' },
  { key: 'bandcamp', name: 'Bandcamp' },
  { key: 'apple-music', name: 'Apple Music' },
  { key: 'mastodon', name: 'Mastodon' },
  { key: 'bluesky', name: 'Bluesky' },
  { key: 'tumblr', name: 'Tumblr' },
  { key: 'vimeo', name: 'Vimeo' },
  { key: 'patreon', name: 'Patreon' },
  { key: 'kofi', name: 'Ko-fi' },
  { key: 'buymeacoffee', name: 'Buy Me a Coffee' },
  { key: 'gumroad', name: 'Gumroad' },
  { key: 'cashapp', name: 'Cash App' },
  { key: 'venmo', name: 'Venmo' },
  { key: 'quora', name: 'Quora' },
  { key: 'flickr', name: 'Flickr' },
  { key: 'vsco', name: 'VSCO' },
  { key: 'clubhouse', name: 'Clubhouse' },
  { key: 'bereal', name: 'BeReal' },
  { key: 'letterboxd', name: 'Letterboxd' },
  { key: 'goodreads', name: 'Goodreads' },
  { key: 'producthunt', name: 'Product Hunt' },
  { key: 'devto', name: 'Dev.to' },
  { key: 'stackoverflow', name: 'Stack Overflow' },
  { key: 'codepen', name: 'CodePen' },
  { key: 'figma', name: 'Figma' },
  { key: 'notion', name: 'Notion' },
  { key: 'steam', name: 'Steam' },
  { key: 'kick', name: 'Kick' },
  { key: 'rumble', name: 'Rumble' },
  { key: 'strava', name: 'Strava' },
  { key: 'tiktok', name: 'TikTok' },
];
